---
  # path to maven: optional if you have it added to your env path.
  maven: /opt/maven
  java:
    # path to your JAVA_HOME. optional if you have JAVA_HOME in your path
    home8:  /usr/lib/jvm/java-8-openjdk-amd64/
  tmp_large_memory:
    # where the repository will be cloned.
    repos_path:  ~/code/mBERTa/tmp/mvn_projects
  exec:
    # set this to true if you want to execute a fresh rerun
    force_reload: False
    # number of mutants to be executed in parallel.
    max_processes: 4
    # number of processus to pass to pytorch to enhance prediction speed.
    # Make sure to not exceed your maximum number of CPUs.
    torch_processes: 8
    # Keep this to true if you want to include all the business-logic lines of code.
    all_lines: True
    # Turn this to True if you want to remove the comments and javadoc before the mutation.
    no_comments: False
    # Turn this to True if you want to mask the full if conditions.
    mask_full_conditions: False
    # Turn this to True if you want to generate only simple mutants without the condition seeding ones.
    simple_only: True

    language_model:
        model_name: codeBERT
        context_size: 512
    # Maximum time to run tests on a mutant. Default is 5 minutes.
    tests_timeout: 300
    # Turn this to true to remove the cloned repo on exit. This is useful when you are conducting a study on remote repositories.
    # Make sure this is False if you are targeting a local repository.
    # by default, if a -git_url is given, the clone will be removed in the end, otherwise not.
    remove_project_on_exit:
  # this is where the results will be output.
  output_dir:  ~/code/mBERTa/tmp/output-mbert
...
